"""Observer Profile bootstrapper — creates + maintains the auto-generated
observer profile that a Room uses to route messages.

Design reference: docs/design/agent-room/design.html §5 (observer construction),
§8 (cross-member summary Rule A — SOUL.md instruction).

Design constraints (from HTML §5.1):
  - observer profile is a normal profile directory, but with 4 special
    conventions:
    * SOUL.md is auto-generated from the room's member roster, regenerated
      on every member change (§5.2 template, §8 Rule A summary instruction)
    * config.yaml has toolsets: [room_observer] — the single-toolset lockdown
      that Spike 3 (§9.1) confirmed genuinely restricts the observer's
      behavior to just route_to_member
    * profile.yaml has description + description_auto: true, marking it
      as machine-generated so /agent list can badge it and /agent delete
      can refuse to strand a live room
    * .observer marker file — an empty sentinel that lets any external
      tool distinguish "hand-crafted profile" from "auto-generated observer"
      without loading config.yaml
  - memory subsystem is off. Spike 2 (§9.1) confirmed memory.memory_enabled
    defaults to False, so the observer needs nothing explicit to keep memory
    disabled — but we still write `memory: {memory_enabled: false}` as a
    documentation anchor so a reader inspecting config.yaml sees the choice.
  - observer profile is created via hermes_cli.profiles.create_profile with
    clone_env=False, clone_skills=False, no_skills=True — a completely blank
    profile. No source profile's .env or skills leak in.

The store row is written by M1.5's slash-command handler AFTER
build_observer_profile() succeeds, so a failed bootstrap leaves no
inconsistent agent_rooms row pointing at a missing profile directory.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from hermes_cli.profiles import (
    create_profile,
    delete_profile,
    get_profile_dir,
    normalize_profile_name,
    write_profile_meta,
)
from utils import atomic_yaml_write


# Marker file inside <observer_profile>/ signalling "auto-generated by
# agent_room_bootstrapper". Absent from hand-crafted profiles.
OBSERVER_MARKER_FILENAME = ".observer"

# Slug regex used when building an observer profile name from a room_name.
# Matches the profile-name rules validated by hermes_cli.profiles: lowercase
# alphanumerics + hyphen + underscore. Anything else in room_name (spaces,
# CJK, emoji, punctuation) becomes a single underscore.
_SLUG_STRIPPER = re.compile(r"[^a-z0-9_-]+")


class BootstrapError(RuntimeError):
    """Raised when observer profile creation cannot complete cleanly."""


def observer_profile_name_for(room_name: str) -> str:
    """Deterministic observer profile name for a given room_name.

    Format: ``room_<slug>_observer``. Empty slug (all non-slugifiable input)
    falls back to a hash-free prefix ``room_x_observer`` — callers should
    prefer meaningful room names to avoid collisions, but this at least
    yields a valid profile name for any input.
    """
    slug = _SLUG_STRIPPER.sub("_", str(room_name or "").strip().lower()).strip("_")
    if not slug:
        slug = "x"
    return f"room_{slug}_observer"


def is_observer_profile(profile_dir: Path) -> bool:
    """True iff *profile_dir* was created by this bootstrapper.

    Used by /agent delete + /room delete to distinguish user-owned profiles
    from auto-generated observers, so deleting a room can cascade to its
    observer safely while `hermes profile delete <observer>` can warn.
    """
    return (profile_dir / OBSERVER_MARKER_FILENAME).is_file()


# ---------------------------------------------------------------------------
# SOUL.md rendering (§5.2 template + §8 Rule A instruction)
# ---------------------------------------------------------------------------


def _render_member_line(member_name: str, member_description: str) -> str:
    desc = str(member_description or "").strip() or "(no description)"
    return f"- **{member_name}**: {desc}"


def render_observer_soul_md(
    *,
    room_name: str,
    room_description: str,
    members: list[tuple[str, str]],
    default_member: str,
) -> str:
    """Render the observer's SOUL.md.

    Parameters
    ----------
    room_name : str
        User-visible room name, injected into the SOUL header.
    room_description : str
        Free-form room purpose (may be empty).
    members : list[tuple[str, str]]
        Ordered ``(profile_name, description)`` pairs for the roster.
    default_member : str
        Fallback routing target (guaranteed by AgentRoom.resolve_default_member
        to be a real member — bootstrapper doesn't second-guess it).

    The output includes §8 Rule A — the "话题延续换成员时 reason 带摘要"
    instruction — as an explicit workflow step, so the observer produces
    the reason field with the previous member's summary when it switches
    members mid-topic. M1.5's router reads that summary out and prefixes
    it onto the receiving member's message (§8 Rule B).
    """
    member_lines = "\n".join(
        _render_member_line(name, desc) for name, desc in members
    )
    description = (room_description or "").strip() or "(no description)"

    return f"""# Observer Agent for Room: {room_name}

You are the observer for a group of specialized agents. Your job is to read
incoming messages and decide which member should respond.

## Room description
{description}

## Members
{member_lines}

## Your workflow
1. Read the latest message (see conversation history).
2. Determine whether this is a NEW topic or a continuation.
   - Continuation: keep routing to the same member as last time.
   - New topic: pick the best-matching member by their descriptions.
3. When switching to a DIFFERENT member than last time on a continuing
   topic, include a 1-sentence summary of the previous member's last reply
   in the `reason` field, prefixed with "上一位处理人 <name> 的回复摘要:".
   The router will forward this summary to the new member so they don't
   lose context. (§8 cross-member summary — M1 UX-cliff mitigation.)
4. Emit your routing decision by calling `route_to_member` with:
   - `member`: profile name from the roster above
   - `reason`: 1-sentence explanation (+ optional summary per step 3)
   - `is_new_topic`: true if you consider this a new topic

If ambiguous → route to `{default_member}` with reason "fallback".

Do NOT write any user-facing reply yourself.
Your only output is the `route_to_member` tool call.
"""


def _inherit_credentials(profile_dir: Path) -> None:
    """Copy .env and auth.json from the default profile (~/.hermes) into
    the observer profile so its LLM calls have the same API key.

    Without this, the observer profile has no credentials → the alibaba
    provider defaults to dashscope-intl (auth.json's hardcoded base_url)
    while the key is for dashscope (domestic) → 401 AuthenticationError.

    This is a deliberate exception to the "blank profile" design: the
    observer MUST call the LLM to emit route_to_member, so it needs
    credentials. Skills and toolsets remain locked down — only .env
    and auth.json (credential files) are inherited.
    """
    import shutil
    from hermes_constants import get_hermes_home

    default_home = get_hermes_home()
    for filename in (".env", "auth.json"):
        src = default_home / filename
        dst = profile_dir / filename
        if src.is_file():
            try:
                shutil.copy2(src, dst)
                if filename == ".env":
                    import os
                    os.chmod(dst, 0o600)
            except Exception:
                pass  # best-effort — observer still works if gateway has global key


# ---------------------------------------------------------------------------
# Profile directory construction / regeneration / teardown
# ---------------------------------------------------------------------------


def _observer_config_yaml() -> dict[str, Any]:
    """The observer profile's config.yaml contents.

    * ``toolsets: [room_observer]`` — enforces the single-tool lockdown
      confirmed by Spike 3 (§9.1). No _HERMES_CORE_TOOLS leak in.
    * ``memory.memory_enabled: false`` — anchoring documentation. Field
      defaults to False anyway per Spike 2 (§9.1), but writing it makes
      the intent explicit to a human reader.
    * ``tools.tool_search.enabled: off`` — tool_search's tier-1 mechanism
      re-adds _HERMES_CORE_TOOLS regardless of enabled_toolsets (live bug
      found during DingTalk testing). Disabling it here is belt-and-
      suspenders alongside the _LockedTools runtime guard in
      TurnRunner.run_sync.
    * ``model`` section inherited from the default profile's config.yaml
      so the observer's LLM calls use the same provider/base_url/model
      as the rest of the gateway (e.g. alibaba → domestic dashscope URL,
      not the intl default in auth.json that causes 401).
    """
    import yaml as _yaml
    from hermes_constants import get_hermes_home

    config: dict[str, Any] = {
        "toolsets": ["room_observer"],
        "memory": {"memory_enabled": False},
        "tools": {"tool_search": {"enabled": "off"}},
    }

    # Inherit model config from the default profile (~/.hermes/config.yaml)
    # so the observer uses the same provider/base_url/model. Without this
    # the agent falls back to auth.json's base_url (dashscope-intl) which
    # may not match the API key → 401.
    try:
        default_config_path = get_hermes_home() / "config.yaml"
        if default_config_path.is_file():
            with open(default_config_path, "r", encoding="utf-8") as f:
                default_cfg = _yaml.safe_load(f) or {}
            if isinstance(default_cfg.get("model"), dict):
                config["model"] = default_cfg["model"]
    except Exception:
        pass  # best-effort — observer still works if gateway has global key

    return config


def _write_config_yaml(profile_dir: Path) -> None:
    atomic_yaml_write(profile_dir / "config.yaml", _observer_config_yaml())


def _write_soul_md(
    profile_dir: Path,
    *,
    room_name: str,
    room_description: str,
    members: list[tuple[str, str]],
    default_member: str,
) -> None:
    (profile_dir / "SOUL.md").write_text(
        render_observer_soul_md(
            room_name=room_name,
            room_description=room_description,
            members=members,
            default_member=default_member,
        ),
        encoding="utf-8",
    )


def _touch_marker(profile_dir: Path) -> None:
    (profile_dir / OBSERVER_MARKER_FILENAME).touch()


def build_observer_profile(
    *,
    room_name: str,
    room_description: str,
    members: list[tuple[str, str]],
    default_member: str,
    observer_name: str | None = None,
) -> Path:
    """Create the observer profile directory + write SOUL.md / config.yaml /
    profile.yaml + .observer marker.

    ``observer_name``, when None, is derived from ``room_name`` via
    ``observer_profile_name_for``. Callers passing an explicit name are
    responsible for choosing a valid profile identifier.

    Returns the created profile directory path.

    Raises BootstrapError if:
      - the observer name collides with an EXISTING profile (M1-B1 territory,
        but here caught pre-create rather than at Store insert time — we
        do NOT overwrite a directory we didn't create, because that would
        clobber a user-owned profile that happens to have the same name.
        Callers should propagate this back as a "room name collision" to
        the user).
      - profile creation raises anything (disk full, permission, etc.);
        no partial state is left behind because create_profile is itself
        atomic-ish and we call teardown_observer_profile on any failure.
    """
    name = normalize_profile_name(
        observer_name if observer_name else observer_profile_name_for(room_name)
    )

    profile_dir = get_profile_dir(name)
    if profile_dir.exists():
        # If the pre-existing directory is a stale observer from a crashed
        # earlier bootstrap, we could reclaim it — but conservatively we
        # refuse and let the caller resolve. Reclaim logic (M1-B9 cousin)
        # is a bootstrapper-scan concern, not an in-line create decision.
        raise BootstrapError(
            f"cannot bootstrap observer: profile {name!r} already exists "
            f"at {profile_dir}; pick a different room name or clean up "
            f"the stale directory"
        )

    try:
        create_profile(
            name,
            clone_from=None,
            clone_all=False,
            clone_config=False,
            clone_env=False,      # do NOT inherit any source profile's .env
            clone_skills=False,   # do NOT inherit skills — Spike 3 lockdown
            no_alias=True,        # observer is invisible to shell users
            no_skills=True,       # explicit "no skills seeded" marker
            description=None,     # profile.yaml written below
        )
    except Exception as exc:
        # Best-effort cleanup: if create_profile crashed after the mkdir but
        # before finishing, the directory might exist and leak. Try to remove.
        if profile_dir.exists():
            try:
                delete_profile(name, yes=True)
            except Exception:
                pass
        raise BootstrapError(f"failed to create observer profile: {exc}") from exc

    # Inherit credentials from the default profile (~/.hermes) so the
    # observer's LLM calls succeed. create_profile with clone_env=False
    # intentionally leaves the new profile with no .env — but the observer
    # MUST call the LLM (to emit route_to_member), so it needs the same
    # API key the gateway uses. Copy .env and auth.json from the default
    # profile; config.yaml's model section is inherited via
    # _observer_config_yaml() below.
    _inherit_credentials(profile_dir)

    # Write config.yaml (overwriting default), SOUL.md (overwriting the
    # DEFAULT_SOUL_MD that create_profile seeds), profile.yaml metadata,
    # and the .observer marker in that order. If any of these fail we tear
    # the whole directory down — a half-configured observer is worse than
    # no observer at all.
    try:
        _write_config_yaml(profile_dir)
        _write_soul_md(
            profile_dir,
            room_name=room_name,
            room_description=room_description,
            members=members,
            default_member=default_member,
        )
        write_profile_meta(
            profile_dir,
            description=f"Room observer for {room_name}",
            description_auto=True,
        )
        _touch_marker(profile_dir)
    except Exception as exc:
        try:
            delete_profile(name, yes=True)
        except Exception:
            pass
        raise BootstrapError(f"failed to write observer profile files: {exc}") from exc

    return profile_dir


def regenerate_observer_soul(
    *,
    observer_profile: str,
    room_name: str,
    room_description: str,
    members: list[tuple[str, str]],
    default_member: str,
) -> None:
    """Overwrite the observer's SOUL.md after a room member change.

    Called by M1.5's `/room members add|remove` handler AFTER the store
    row has been updated (so this reflects the new roster) and BEFORE
    unfencing any sessions.

    Refuses to touch a directory that isn't marked as an observer profile,
    so a bug in caller code can't accidentally overwrite a user's SOUL.md.
    """
    name = normalize_profile_name(observer_profile)
    profile_dir = get_profile_dir(name)
    if not profile_dir.is_dir():
        raise BootstrapError(
            f"observer profile {name!r} does not exist at {profile_dir}"
        )
    if not is_observer_profile(profile_dir):
        raise BootstrapError(
            f"profile {name!r} is not marked as an auto-generated observer "
            f"({OBSERVER_MARKER_FILENAME} missing); refusing to overwrite "
            f"a hand-crafted SOUL.md"
        )
    _write_soul_md(
        profile_dir,
        room_name=room_name,
        room_description=room_description,
        members=members,
        default_member=default_member,
    )


def teardown_observer_profile(observer_profile: str) -> bool:
    """Delete the observer profile directory.

    Idempotent (M1-B9): if the directory is already gone, return False
    without raising. If the directory exists but is NOT marked as an
    observer, refuse — this prevents `/room delete` from clobbering a
    user's manually-created profile that happens to share a room's
    observer naming convention.

    Returns True iff a directory was actually removed.
    """
    try:
        name = normalize_profile_name(observer_profile)
    except ValueError:
        return False
    profile_dir = get_profile_dir(name)
    if not profile_dir.is_dir():
        return False
    if not is_observer_profile(profile_dir):
        raise BootstrapError(
            f"refusing to teardown {name!r}: {OBSERVER_MARKER_FILENAME} "
            f"marker missing — not an auto-generated observer profile"
        )
    delete_profile(name, yes=True)
    return True
