import type { Locale, Translations } from "@/i18n";

const ACRONYMS = new Set([
  "api",
  "cdp",
  "cli",
  "cpu",
  "cwd",
  "id",
  "json",
  "llm",
  "mb",
  "mcp",
  "ms",
  "oauth",
  "pii",
  "stt",
  "tts",
  "tui",
  "url",
  "urls",
  "yaml",
]);

const ZH_SECTION_LABELS: Record<string, string> = {
  agent: "代理",
  auxiliary: "辅助模型",
  browser: "浏览器",
  compression: "上下文压缩",
  dashboard: "Dashboard",
  delegation: "子代理委托",
  dingtalk: "钉钉",
  discord: "Discord",
  display: "显示",
  gateway: "网关",
  general: "通用",
  human_delay: "模拟人类延迟",
  logging: "日志",
  memory: "记忆",
  model: "模型",
  security: "安全",
  stt: "语音转文字",
  terminal: "终端",
  tts: "文字转语音",
  voice: "语音",
  web: "Web",
  tool_output: "工具输出",
  tool_loop_guardrails: "工具循环护栏",
  openrouter: "OpenRouter",
  bedrock: "AWS Bedrock",
  curator: "语料整理",
  slack: "Slack",
  mattermost: "Mattermost",
  matrix: "Matrix",
  kanban: "看板",
  tools: "工具",
  model_catalog: "模型目录",
  streaming: "流式传输",
  sessions: "会话",
  lsp: "LSP服务",
  x_search: "X 搜索",
  secrets: "机密",
};

const ZH_FIELD_LABELS: Record<string, string> = {
  model: "默认模型",
  model_context_length: "模型上下文长度",
  "agent.max_turns": "最大轮次",
  "agent.gateway_timeout": "网关超时",
  "agent.native_image_max_base64_bytes": "原生图片压缩阈值",
  "agent.restart_drain_timeout": "重启等待时间",
  "agent.service_tier": "服务等级",
  "dashboard.theme": "Dashboard 主题",
  "dashboard.show_token_analytics": "显示 Token 统计",
  "delegation.reasoning_effort": "子代理推理强度",
  "display.busy_input_mode": "忙碌时输入模式",
  "display.resume_display": "恢复会话显示方式",
  "display.skin": "CLI 皮肤",
  "dingtalk.agent_id": "钉钉 AgentId",
  "dingtalk.allow_all_users": "允许所有钉钉用户",
  "dingtalk.allowed_chats": "允许的钉钉群",
  "dingtalk.allowed_users": "允许的钉钉用户",
  "dingtalk.app_code": "钉钉 appCode",
  "dingtalk.card_content_key": "AI Card 内容字段",
  "dingtalk.card_template_id": "AI Card 模板 ID",
  "dingtalk.corp_id": "钉钉 CorpId",
  "dingtalk.free_response_chats": "免 @ 回复群",
  "dingtalk.reply_at_sender": "回复时 @ 发送者",
  "dingtalk.require_mention": "需要 @ 才回复",
  "logging.level": "日志级别",
  "memory.provider": "记忆提供方",
  "terminal.backend": "终端后端",
  "terminal.cwd": "工作目录",
  "terminal.timeout": "命令超时",
  "terminal.vercel_runtime": "Vercel 运行时",
};

const ZH_FIELD_WORDS: Record<string, string> = {
  abort: "中止",
  accept: "接受",
  access: "访问",
  ack: "确认",
  acked: "已确认",
  actions: "动作",
  adopt: "采纳",
  advisories: "建议",
  after: "之后",
  agent: "代理",
  agents: "代理",
  alias: "别名",
  allow: "允许",
  allowed: "允许的",
  allowlist: "白名单",
  ambient: "环境",
  analytics: "统计",
  any: "任意",
  api: "API",
  approval: "批准",
  approve: "批准",
  archive: "归档",
  args: "参数",
  as: "作为",
  assignee: "负责人",
  assistant: "助手",
  attachment: "附件",
  audio: "音频",
  auth: "认证",
  auto: "自动",
  autoraise: "自动唤醒",
  backend: "后端",
  backfill: "回填",
  backup: "备份",
  base: "基础",
  bashrc: "bashrc",
  beep: "提示音",
  bell: "响铃",
  bit: "位",
  buffer: "缓冲",
  build: "构建",
  builtins: "内置",
  busy: "忙碌",
  bytes: "字节",
  cache: "缓存",
  cdp: "CDP",
  changes: "变更",
  channels: "频道",
  char: "字符",
  chars: "字符",
  chats: "聊天",
  child: "子级",
  children: "子项",
  clarify: "澄清",
  client: "客户端",
  code: "代码",
  codex: "法典",
  coding: "编码",
  collapse: "折叠",
  command: "命令",
  compact: "紧凑",
  complete: "完成",
  completion: "补全",
  concurrent: "并发",
  confirm: "确认",
  container: "容器",
  context: "上下文",
  continue: "继续",
  copy: "复制",
  cost: "成本",
  count: "计数",
  cpu: "CPU",
  created: "创建于",
  credits: "额度",
  cron: "定时任务",
  cursor: "光标",
  cwd: "工作目录",
  days: "天",
  daytona: "Daytona",
  decompose: "分解",
  default: "默认",
  delete: "删除",
  delivery: "投递",
  depth: "深度",
  destructive: "破坏性",
  device: "设备",
  dialog: "对话框",
  diarize: "角色分离",
  diffs: "差异",
  dirs: "目录",
  disabled: "禁用",
  disk: "磁盘",
  dispatch: "派发",
  display: "显示",
  dm: "私聊",
  docker: "Docker",
  domains: "域名",
  download: "下载",
  drain: "排空",
  duck: "闪避",
  duration: "时长",
  edit: "编辑",
  effort: "力度",
  enabled: "启用",
  enforcement: "执行",
  engine: "引擎",
  env: "环境变量",
  environment: "环境",
  ephemeral: "临时的",
  events: "事件",
  exact: "精确",
  exchanges: "交换",
  existing: "现有的",
  explainer: "解释器",
  external: "外部",
  extra: "额外",
  extract: "提取",
  fail: "失败",
  failure: "失败",
  fallback: "降级",
  fields: "字段",
  file: "文件",
  files: "文件",
  filter: "过滤",
  final: "最终",
  first: "首个",
  for: "用于",
  force: "强制",
  forward: "转发",
  free: "免费",
  fresh: "新鲜",
  freshness: "新鲜度",
  gain: "增益",
  gateway: "网关",
  gpt55: "GPT5.5",
  guard: "守卫",
  guardrail: "护栏",
  guidance: "引导",
  guild: "服务器",
  hard: "硬",
  hash: "哈希",
  hint: "提示",
  history: "历史",
  hooks: "钩子",
  host: "主机",
  hours: "小时",
  hygiene: "卫生",
  id: "ID",
  idempotent: "幂等",
  identifier: "标识符",
  idle: "空闲",
  image: "图片",
  in: "在",
  inactivity: "不活跃",
  indicator: "指示器",
  inherit: "继承",
  init: "初始化",
  inline: "内联",
  input: "输入",
  install: "安装",
  installs: "安装",
  interactive: "交互式",
  interface: "接口",
  interim: "临时",
  interval: "间隔",
  ipv4: "IPv4",
  iterations: "迭代",
  jobs: "任务",
  json: "JSON",
  keep: "保持",
  key: "密钥",
  language: "语言",
  last: "最近",
  lazy: "懒加载",
  length: "长度",
  level: "级别",
  limit: "限制",
  line: "行",
  lines: "行",
  local: "本地",
  log: "日志",
  loopback: "环回",
  managed: "托管",
  markdown: "Markdown",
  max: "最大",
  mb: "MB",
  mcp: "MCP",
  media: "媒体",
  memory: "记忆",
  mention: "@",
  message: "消息,",
  messages: "消息",
  min: "最小",
  modal: "模态框",
  mode: "模式",
  model: "模型",
  mount: "挂载",
  ms: "毫秒",
  mutation: "变更",
  n: "N",
  no: "无",
  non: "非",
  notices: "通知",
  notify: "通知",
  nudge: "轻推",
  on: "开启",
  only: "仅",
  open: "打开",
  orchestrator: "编排器",
  orphans: "孤儿",
  output: "输出",
  override: "覆盖",
  parallel: "并行",
  passthrough: "透传",
  password: "密码",
  paste: "粘贴",
  path: "路径",
  pct: "百分比",
  per: "每次",
  persist: "持久化",
  persistence: "持久化",
  persistent: "持久化的",
  persona: "人设",
  personality: "性格",
  phrases: "短语",
  pii: "PII",
  policy: "策略",
  portal: "门户",
  pre: "预",
  prefill: "预填充",
  preview: "预览",
  private: "私有",
  probe: "探针",
  processing: "处理",
  profile: "配置档",
  progress: "进度",
  project: "项目",
  prompt: "提示词",
  prompts: "提示词",
  protect: "保护",
  provider: "提供方",
  providers: "提供商",
  prune: "清理",
  public: "公开",
  rate: "速率",
  ratio: "比例",
  reactions: "回应",
  read: "读取",
  reasoning: "推理",
  recent: "最近",
  record: "记录",
  recording: "录制",
  redact: "脱敏",
  ref: "引用",
  refresh: "刷新",
  region: "区域",
  reload: "重载",
  require: "需要",
  response: "回复",
  restart: "重启",
  resume: "恢复",
  retention: "保留",
  retries: "重试",
  rewrite: "重写",
  role: "角色",
  rooms: "房间",
  rotate: "轮换",
  run: "运行",
  s: "秒",
  same: "相同",
  sample: "采样",
  score: "分数",
  search: "搜索",
  seconds: "秒",
  secret: "机密",
  secrets: "机密",
  server: "服务器",
  service: "服务",
  session: "会话",
  sessions: "会话",
  shared: "共享",
  shell: "Shell",
  shortcut: "快捷键",
  show: "显示",
  silence: "静音",
  singularity: "奇点",
  size: "大小",
  skin: "皮肤",
  skip: "跳过",
  slash: "斜杠",
  snapshots: "快照",
  source: "来源",
  spawn: "派生",
  speech: "语音",
  stale: "过时",
  status: "状态",
  stop: "停止",
  strategy: "策略",
  stream: "流式",
  streaming: "流式传输",
  strict: "严格",
  subagent: "子代理",
  summary: "总结",
  system: "系统",
  tab: "标签页",
  tag: "标签",
  tags: "标签",
  target: "目标",
  task: "任务",
  template: "模板",
  text: "文本",
  theme: "主题",
  thread: "线程",
  threshold: "阈值",
  tick: "跳动",
  tier: "层级",
  timeout: "超时",
  timestamps: "时间戳",
  timezone: "时区",
  tirith: "Tirith",
  to: "到",
  token: "Token",
  tool: "工具",
  toolsets: "工具集",
  total: "总计",
  trace: "追踪",
  transport: "传输",
  trust: "信任",
  ttl: "TTL",
  tts: "TTS",
  tui: "TUI",
  turn: "轮次",
  turns: "轮次",
  update: "更新",
  url: "URL",
  urls: "URL",
  use: "使用",
  user: "用户",
  username: "用户名",
  vacuum: "清理",
  vars: "变量",
  verifier: "验证器",
  version: "版本",
  voice: "声音",
  volumes: "卷",
  wait: "等待",
  warning: "警告",
  warnings: "警告",
  worker: "工作者",
  workspace: "工作区",
  wrap: "换行",
  write: "写入",
};

const ZH_DESCRIPTIONS: Record<string, string> = {
  model: "默认使用的模型，例如 anthropic/claude-sonnet-4.6。",
  model_context_length: "手动覆盖上下文窗口；0 表示根据模型元数据自动判断。",
  "agent.max_turns": "单次任务允许的最大工具调用/模型循环轮次。",
  "agent.gateway_timeout": "网关中代理完全空闲多久后视为超时，单位秒。",
  "agent.native_image_max_base64_bytes": "原生图片传给主模型前的主动压缩阈值，单位为 base64 字节；0 表示关闭主动压缩。",
  "agent.restart_drain_timeout": "网关重启时等待正在运行任务收尾的最长时间，单位秒。",
  "dashboard.theme": "Web Dashboard 的视觉主题。",
  "dashboard.show_token_analytics": "显示本地估算的 token/cost 统计；该数值不是账单口径。",
  "dingtalk.agent_id": "钉钉企业内部应用 AgentId；当前仅保存并透传，后续接工作通知等 API 时使用。",
  "dingtalk.allow_all_users": "允许所有钉钉用户通过网关鉴权；关闭时应配置用户 allowlist。",
  "dingtalk.allowed_chats": "仅允许这些钉钉群触发机器人，多个 ID 用逗号分隔。",
  "dingtalk.allowed_users": "允许的钉钉 staff_id 或 sender_id，多个值用逗号分隔；* 表示任意用户。",
  "dingtalk.app_code": "钉钉应用 appCode；当前仅保存并透传，现有 Stream 机器人收发不读取它。",
  "dingtalk.card_content_key": "钉钉 AI Card 模板中用于承载回复内容的变量名；留空时使用 msgContent。",
  "dingtalk.card_template_id": "钉钉 AI Card 模板 ID；留空时使用钉钉 SDK 默认 Markdown 卡片。",
  "dingtalk.corp_id": "钉钉企业 CorpId；当前仅保存并透传，后续接企业级开放接口时使用。",
  "dingtalk.free_response_chats": "这些钉钉群里无需 @ 机器人也会响应，多个 ID 用逗号分隔。",
  "dingtalk.reply_at_sender": "开启后，群聊最终回复会 @ 触发这轮对话的发送者。",
  "dingtalk.require_mention": "开启后，钉钉群聊里只有 @ 机器人时才响应。",
  "terminal.backend": "工具执行使用的终端后端，例如 local、docker、ssh。",
  "terminal.cwd": "网关和工具执行的默认工作目录。",
};

function isChinese(locale: Locale): boolean {
  return locale === "zh";
}

function fallbackSegmentLabel(segment: string): string {
  return segment
    .split("_")
    .filter(Boolean)
    .map((word) => {
      const lower = word.toLowerCase();
      if (ACRONYMS.has(lower)) return lower.toUpperCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(" ");
}

function fallbackPathLabel(schemaKey: string): string {
  return schemaKey
    .replace(/\./g, " → ")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function translateSegment(segment: string, locale: Locale, kind: "field" | "section"): string {
  if (!isChinese(locale)) return fallbackSegmentLabel(segment);
  if (kind === "section" && ZH_SECTION_LABELS[segment]) return ZH_SECTION_LABELS[segment];
  if (kind === "field" && ZH_FIELD_LABELS[segment]) return ZH_FIELD_LABELS[segment];

  const words = segment
    .split("_")
    .filter(Boolean)
    .map((word) => ZH_FIELD_WORDS[word.toLowerCase()] ?? "");
  if (words.length > 0 && words.every(Boolean)) return words.join("");
  return fallbackSegmentLabel(segment);
}

export function formatConfigCategoryName(
  category: string,
  t: Translations,
  locale: Locale,
): string {
  const knownCategory = (t.config.categories as Record<string, string>)[category];
  if (isChinese(locale) && ZH_SECTION_LABELS[category]) return ZH_SECTION_LABELS[category];
  if (knownCategory) return knownCategory;
  return translateSegment(category, locale, "section");
}

export function formatConfigSectionName(section: string, locale: Locale): string {
  return translateSegment(section, locale, "section");
}

export function formatConfigFieldLabel(schemaKey: string, locale: Locale): string {
  if (isChinese(locale) && ZH_FIELD_LABELS[schemaKey]) return ZH_FIELD_LABELS[schemaKey];
  const rawLabel = schemaKey.split(".").pop() ?? schemaKey;
  return translateSegment(rawLabel, locale, "field");
}

export function formatConfigPathLabel(schemaKey: string, locale: Locale): string {
  return schemaKey
    .split(".")
    .map((part, idx, parts) =>
      idx === parts.length - 1
        ? formatConfigFieldLabel(schemaKey, locale)
        : formatConfigSectionName(part, locale),
    )
    .join(" → ");
}

export function formatConfigDescription(
  schemaKey: string,
  schema: Record<string, unknown>,
  locale: Locale,
): string {
  if (isChinese(locale) && ZH_DESCRIPTIONS[schemaKey]) return ZH_DESCRIPTIONS[schemaKey];

  const description = schema.description ? String(schema.description) : "";
  if (!description) return "";
  if (isChinese(locale) && description === fallbackPathLabel(schemaKey)) {
    return formatConfigPathLabel(schemaKey, locale);
  }
  return description;
}
