import type { Locale, Translations } from "@/i18n";

const ACRONYMS = new Set([
  "api",
  "cdp",
  "cli",
  "cpu",
  "cwd",
  "id",
  "json",
  "llm",
  "mb",
  "mcp",
  "ms",
  "oauth",
  "pii",
  "stt",
  "tts",
  "tui",
  "url",
  "urls",
  "yaml",
]);

const ZH_SECTION_LABELS: Record<string, string> = {
  agent: "代理",
  auxiliary: "辅助模型",
  browser: "浏览器",
  compression: "上下文压缩",
  dashboard: "Dashboard",
  delegation: "子代理委托",
  dingtalk: "钉钉",
  discord: "Discord",
  display: "显示",
  gateway: "网关",
  general: "通用",
  human_delay: "模拟人类延迟",
  logging: "日志",
  memory: "记忆",
  model: "模型",
  security: "安全",
  stt: "语音转文字",
  terminal: "终端",
  tts: "文字转语音",
  voice: "语音",
  web: "Web",
  tool_output: "工具输出",
  tool_loop_guardrails: "工具循环护栏",
  openrouter: "OpenRouter",
  bedrock: "AWS Bedrock",
  curator: "语料整理",
  slack: "Slack",
  mattermost: "Mattermost",
  matrix: "Matrix",
  kanban: "看板",
  tools: "工具",
  model_catalog: "模型目录",
  streaming: "流式传输",
  sessions: "会话",
  lsp: "LSP服务",
  x_search: "X 搜索",
  secrets: "机密",
};

const ZH_FIELD_LABELS: Record<string, string> = {
  model: "默认模型",
  model_context_length: "模型上下文长度",
  "agent.max_turns": "最大轮次",
  "agent.gateway_timeout": "网关超时",
  "agent.native_image_max_base64_bytes": "原生图片压缩阈值",
  "agent.restart_drain_timeout": "重启等待时间",
  "agent.service_tier": "服务等级",
  "dashboard.theme": "Dashboard 主题",
  "dashboard.show_token_analytics": "显示 Token 统计",
  "delegation.reasoning_effort": "子代理推理强度",
  "display.busy_input_mode": "忙碌时输入模式",
  "display.resume_display": "恢复会话显示方式",
  "display.skin": "CLI 皮肤",
  "dingtalk.agent_id": "钉钉 AgentId",
  "dingtalk.allow_all_users": "允许所有钉钉用户",
  "dingtalk.allowed_chats": "允许的钉钉群",
  "dingtalk.allowed_users": "允许的钉钉用户",
  "dingtalk.app_code": "钉钉 appCode",
  "dingtalk.card_content_key": "AI Card 内容字段",
  "dingtalk.card_template_id": "AI Card 模板 ID",
  "dingtalk.corp_id": "钉钉 CorpId",
  "dingtalk.free_response_chats": "免 @ 回复群",
  "dingtalk.reply_at_sender": "回复时 @ 发送者",
  "dingtalk.require_mention": "需要 @ 才回复",
  "logging.level": "日志级别",
  "memory.provider": "记忆提供方",
  "terminal.backend": "终端后端",
  "terminal.cwd": "工作目录",
  "terminal.timeout": "命令超时",
  "terminal.vercel_runtime": "Vercel 运行时",
};

const ZH_FIELD_WORDS: Record<string, string> = {
  abort: "中止",
  accept: "接受",
  access: "访问",
  ack: "确认",
  acked: "已确认",
  actions: "动作",
  adopt: "采纳",
  advisories: "建议",
  after: "之后",
  agent: "代理",
  agents: "代理",
  alias: "别名",
  allow: "允许",
  allowed: "允许的",
  allowlist: "白名单",
  ambient: "环境",
  analytics: "统计",
  any: "任意",
  api: "API",
  approval: "批准",
  approve: "批准",
  archive: "归档",
  args: "参数",
  as: "作为",
  assignee: "负责人",
  assistant: "助手",
  attachment: "附件",
  audio: "音频",
  auth: "认证",
  auto: "自动",
  autoraise: "自动唤醒",
  backend: "后端",
  backfill: "回填",
  backup: "备份",
  base: "基础",
  bashrc: "bashrc",
  beep: "提示音",
  bell: "响铃",
  bit: "位",
  buffer: "缓冲",
  build: "构建",
  builtins: "内置",
  busy: "忙碌",
  bytes: "字节",
  cache: "缓存",
  cdp: "CDP",
  changes: "变更",
  channels: "频道",
  char: "字符",
  chars: "字符",
  chats: "聊天",
  child: "子级",
  children: "子项",
  clarify: "澄清",
  client: "客户端",
  code: "代码",
  codex: "法典",
  coding: "编码",
  collapse: "折叠",
  command: "命令",
  compact: "紧凑",
  complete: "完成",
  completion: "补全",
  concurrent: "并发",
  confirm: "确认",
  container: "容器",
  context: "上下文",
  continue: "继续",
  copy: "复制",
  cost: "成本",
  count: "计数",
  cpu: "CPU",
  created: "创建于",
  credits: "额度",
  cron: "定时任务",
  cursor: "光标",
  cwd: "工作目录",
  days: "天",
  daytona: "Daytona",
  decompose: "分解",
  default: "默认",
  delete: "删除",
  delivery: "投递",
  depth: "深度",
  destructive: "破坏性",
  device: "设备",
  dialog: "对话框",
  diarize: "角色分离",
  diffs: "差异",
  dirs: "目录",
  disabled: "禁用",
  disk: "磁盘",
  dispatch: "派发",
  display: "显示",
  dm: "私聊",
  docker: "Docker",
  domains: "域名",
  download: "下载",
  drain: "排空",
  duck: "闪避",
  duration: "时长",
  edit: "编辑",
  effort: "力度",
  enabled: "启用",
  enforcement: "执行",
  engine: "引擎",
  env: "环境变量",
  environment: "环境",
  ephemeral: "临时的",
  events: "事件",
  exact: "精确",
  exchanges: "交换",
  existing: "现有的",
  explainer: "解释器",
  external: "外部",
  extra: "额外",
  extract: "提取",
  fail: "失败",
  failure: "失败",
  fallback: "降级",
  fields: "字段",
  file: "文件",
  files: "文件",
  filter: "过滤",
  final: "最终",
  first: "首个",
  for: "用于",
  force: "强制",
  forward: "转发",
  free: "免费",
  fresh: "新鲜",
  freshness: "新鲜度",
  gain: "增益",
  gateway: "网关",
  gpt55: "GPT5.5",
  guard: "守卫",
  guardrail: "护栏",
  guidance: "引导",
  guild: "服务器",
  hard: "硬",
  hash: "哈希",
  hint: "提示",
  history: "历史",
  hooks: "钩子",
  host: "主机",
  hours: "小时",
  hygiene: "卫生",
  id: "ID",
  idempotent: "幂等",
  identifier: "标识符",
  idle: "空闲",
  image: "图片",
  in: "在",
  inactivity: "不活跃",
  indicator: "指示器",
  inherit: "继承",
  init: "初始化",
  inline: "内联",
  input: "输入",
  install: "安装",
  installs: "安装",
  interactive: "交互式",
  interface: "接口",
  interim: "临时",
  interval: "间隔",
  ipv4: "IPv4",
  iterations: "迭代",
  jobs: "任务",
  json: "JSON",
  keep: "保持",
  key: "密钥",
  language: "语言",
  last: "最近",
  lazy: "懒加载",
  length: "长度",
  level: "级别",
  limit: "限制",
  line: "行",
  lines: "行",
  local: "本地",
  log: "日志",
  loopback: "环回",
  managed: "托管",
  markdown: "Markdown",
  max: "最大",
  mb: "MB",
  mcp: "MCP",
  media: "媒体",
  memory: "记忆",
  mention: "@",
  message: "消息,",
  messages: "消息",
  min: "最小",
  modal: "模态框",
  mode: "模式",
  model: "模型",
  mount: "挂载",
  ms: "毫秒",
  mutation: "变更",
  n: "N",
  no: "无",
  non: "非",
  notices: "通知",
  notify: "通知",
  nudge: "轻推",
  on: "开启",
  only: "仅",
  open: "打开",
  orchestrator: "编排器",
  orphans: "孤儿",
  output: "输出",
  override: "覆盖",
  parallel: "并行",
  passthrough: "透传",
  password: "密码",
  paste: "粘贴",
  path: "路径",
  pct: "百分比",
  per: "每次",
  persist: "持久化",
  persistence: "持久化",
  persistent: "持久化的",
  persona: "人设",
  personality: "性格",
  phrases: "短语",
  pii: "PII",
  policy: "策略",
  portal: "门户",
  pre: "预",
  prefill: "预填充",
  preview: "预览",
  private: "私有",
  probe: "探针",
  processing: "处理",
  profile: "配置档",
  progress: "进度",
  project: "项目",
  prompt: "提示词",
  prompts: "提示词",
  protect: "保护",
  provider: "提供方",
  providers: "提供商",
  prune: "清理",
  public: "公开",
  rate: "速率",
  ratio: "比例",
  reactions: "回应",
  read: "读取",
  reasoning: "推理",
  recent: "最近",
  record: "记录",
  recording: "录制",
  redact: "脱敏",
  ref: "引用",
  refresh: "刷新",
  region: "区域",
  reload: "重载",
  require: "需要",
  response: "回复",
  restart: "重启",
  resume: "恢复",
  retention: "保留",
  retries: "重试",
  rewrite: "重写",
  role: "角色",
  rooms: "房间",
  rotate: "轮换",
  run: "运行",
  s: "秒",
  same: "相同",
  sample: "采样",
  score: "分数",
  search: "搜索",
  seconds: "秒",
  secret: "机密",
  secrets: "机密",
  server: "服务器",
  service: "服务",
  session: "会话",
  sessions: "会话",
  shared: "共享",
  shell: "Shell",
  shortcut: "快捷键",
  show: "显示",
  silence: "静音",
  singularity: "奇点",
  size: "大小",
  skin: "皮肤",
  skip: "跳过",
  slash: "斜杠",
  snapshots: "快照",
  source: "来源",
  spawn: "派生",
  speech: "语音",
  stale: "过时",
  status: "状态",
  stop: "停止",
  strategy: "策略",
  stream: "流式",
  streaming: "流式传输",
  strict: "严格",
  subagent: "子代理",
  summary: "总结",
  system: "系统",
  tab: "标签页",
  tag: "标签",
  tags: "标签",
  target: "目标",
  task: "任务",
  template: "模板",
  text: "文本",
  theme: "主题",
  thread: "线程",
  threshold: "阈值",
  tick: "跳动",
  tier: "层级",
  timeout: "超时",
  timestamps: "时间戳",
  timezone: "时区",
  tirith: "Tirith",
  to: "到",
  token: "Token",
  tool: "工具",
  toolsets: "工具集",
  total: "总计",
  trace: "追踪",
  transport: "传输",
  trust: "信任",
  ttl: "TTL",
  tts: "TTS",
  tui: "TUI",
  turn: "轮次",
  turns: "轮次",
  update: "更新",
  url: "URL",
  urls: "URL",
  use: "使用",
  user: "用户",
  username: "用户名",
  vacuum: "清理",
  vars: "变量",
  verifier: "验证器",
  version: "版本",
  voice: "声音",
  volumes: "卷",
  wait: "等待",
  warning: "警告",
  warnings: "警告",
  worker: "工作者",
  workspace: "工作区",
  wrap: "换行",
  write: "写入",
};

const ZH_DESCRIPTIONS: Record<string, string> = {
  model: "默认使用的模型，例如 anthropic/claude-sonnet-4.6。",
  model_context_length: "手动覆盖上下文窗口；0 表示根据模型元数据自动判断。",
  "agent.max_turns": "单次任务允许的最大工具调用/模型循环轮次。",
  "agent.gateway_timeout": "网关中代理完全空闲多久后视为超时，单位秒。",
  "agent.native_image_max_base64_bytes": "原生图片传给主模型前的主动压缩阈值，单位为 base64 字节；0 表示关闭主动压缩。",
  "agent.restart_drain_timeout": "网关重启时等待正在运行任务收尾的最长时间，单位秒。",
  "dashboard.theme": "Web Dashboard 的视觉主题。",
  "dashboard.show_token_analytics": "显示本地估算的 token/cost 统计；该数值不是账单口径。",
  "dingtalk.agent_id": "钉钉企业内部应用 AgentId；当前仅保存并透传，后续接工作通知等 API 时使用。",
  "dingtalk.allow_all_users": "允许所有钉钉用户通过网关鉴权；关闭时应配置用户 allowlist。",
  "dingtalk.allowed_chats": "仅允许这些钉钉群触发机器人，多个 ID 用逗号分隔。",
  "dingtalk.allowed_users": "允许的钉钉 staff_id 或 sender_id，多个值用逗号分隔；* 表示任意用户。",
  "dingtalk.app_code": "钉钉应用 appCode；当前仅保存并透传，现有 Stream 机器人收发不读取它。",
  "dingtalk.card_content_key": "钉钉 AI Card 模板中用于承载回复内容的变量名；留空时使用 msgContent。",
  "dingtalk.card_template_id": "钉钉 AI Card 模板 ID；留空时使用钉钉 SDK 默认 Markdown 卡片。",
  "dingtalk.corp_id": "钉钉企业 CorpId；当前仅保存并透传，后续接企业级开放接口时使用。",
  "dingtalk.free_response_chats": "这些钉钉群里无需 @ 机器人也会响应，多个 ID 用逗号分隔。",
  "dingtalk.reply_at_sender": "开启后，群聊最终回复会 @ 触发这轮对话的发送者。",
  "dingtalk.require_mention": "开启后，钉钉群聊里只有 @ 机器人时才响应。",
  "terminal.backend": "工具执行使用的终端后端，例如 local、docker、ssh。",
  "terminal.cwd": "网关和工具执行的默认工作目录。",
};


const ZH_HANT_SECTION_LABELS: Record<string, string> = {
  agent: "代理",
  auxiliary: "輔助模型",
  browser: "瀏覽器",
  compression: "上下文壓縮",
  dashboard: "Dashboard",
  delegation: "子代理委託",
  dingtalk: "釘釘",
  discord: "Discord",
  display: "顯示",
  gateway: "網關",
  general: "通用",
  human_delay: "模擬人類延遲",
  logging: "日誌",
  memory: "記憶",
  model: "模型",
  security: "安全",
  stt: "語音轉文字",
  terminal: "終端",
  tts: "文字轉語音",
  voice: "語音",
  web: "Web",
  tool_output: "工具輸出",
  tool_loop_guardrails: "工具循環護欄",
  openrouter: "OpenRouter",
  bedrock: "AWS Bedrock",
  curator: "語料整理",
  slack: "Slack",
  mattermost: "Mattermost",
  matrix: "Matrix",
  kanban: "看板",
  tools: "工具",
  model_catalog: "模型目錄",
  streaming: "流式傳輸",
  sessions: "會話",
  lsp: "LSP服務",
  x_search: "X 搜索",
  secrets: "機密",
};

const ZH_HANT_FIELD_LABELS: Record<string, string> = {
  model: "默認模型",
  model_context_length: "模型上下文長度",
  "agent.max_turns": "最大輪次",
  "agent.gateway_timeout": "網關超時",
  "agent.native_image_max_base64_bytes": "原生圖片壓縮閾值",
  "agent.restart_drain_timeout": "重啓等待時間",
  "agent.service_tier": "服務等級",
  "dashboard.theme": "Dashboard 主題",
  "dashboard.show_token_analytics": "顯示 Token 統計",
  "delegation.reasoning_effort": "子代理推理強度",
  "display.busy_input_mode": "忙碌時輸入模式",
  "display.resume_display": "恢復會話顯示方式",
  "display.skin": "CLI 皮膚",
  "dingtalk.agent_id": "釘釘 AgentId",
  "dingtalk.allow_all_users": "允許所有釘釘用戶",
  "dingtalk.allowed_chats": "允許的釘釘羣",
  "dingtalk.allowed_users": "允許的釘釘用戶",
  "dingtalk.app_code": "釘釘 appCode",
  "dingtalk.card_content_key": "AI Card 內容字段",
  "dingtalk.card_template_id": "AI Card 模板 ID",
  "dingtalk.corp_id": "釘釘 CorpId",
  "dingtalk.free_response_chats": "免 @ 回復羣",
  "dingtalk.reply_at_sender": "回復時 @ 發送者",
  "dingtalk.require_mention": "需要 @ 才回復",
  "logging.level": "日誌級別",
  "memory.provider": "記憶提供方",
  "terminal.backend": "終端後端",
  "terminal.cwd": "工作目錄",
  "terminal.timeout": "命令超時",
  "terminal.vercel_runtime": "Vercel 運行時",
};

const ZH_HANT_FIELD_WORDS: Record<string, string> = {
  abort: "中止",
  accept: "接受",
  access: "訪問",
  ack: "確認",
  acked: "已確認",
  actions: "動作",
  adopt: "採納",
  advisories: "建議",
  after: "之後",
  agent: "代理",
  agents: "代理",
  alias: "別名",
  allow: "允許",
  allowed: "允許的",
  allowlist: "白名單",
  ambient: "環境",
  analytics: "統計",
  any: "任意",
  api: "API",
  approval: "批准",
  approve: "批准",
  archive: "歸檔",
  args: "參數",
  as: "作爲",
  assignee: "負責人",
  assistant: "助手",
  attachment: "附件",
  audio: "音頻",
  auth: "認證",
  auto: "自動",
  autoraise: "自動喚醒",
  backend: "後端",
  backfill: "回填",
  backup: "備份",
  base: "基礎",
  bashrc: "bashrc",
  beep: "提示音",
  bell: "響鈴",
  bit: "位",
  buffer: "緩衝",
  build: "構建",
  builtins: "內置",
  busy: "忙碌",
  bytes: "字節",
  cache: "緩存",
  cdp: "CDP",
  changes: "變更",
  channels: "頻道",
  char: "字符",
  chars: "字符",
  chats: "聊天",
  child: "子級",
  children: "子項",
  clarify: "澄清",
  client: "客戶端",
  code: "代碼",
  codex: "法典",
  coding: "編碼",
  collapse: "摺疊",
  command: "命令",
  compact: "緊湊",
  complete: "完成",
  completion: "補全",
  concurrent: "並發",
  confirm: "確認",
  container: "容器",
  context: "上下文",
  continue: "繼續",
  copy: "複製",
  cost: "成本",
  count: "計數",
  cpu: "CPU",
  created: "創建於",
  credits: "額度",
  cron: "定時任務",
  cursor: "光標",
  cwd: "工作目錄",
  days: "天",
  daytona: "Daytona",
  decompose: "分解",
  default: "默認",
  delete: "刪除",
  delivery: "投遞",
  depth: "深度",
  destructive: "破壞性",
  device: "設備",
  dialog: "對話框",
  diarize: "角色分離",
  diffs: "差異",
  dirs: "目錄",
  disabled: "禁用",
  disk: "磁盤",
  dispatch: "派發",
  display: "顯示",
  dm: "私聊",
  docker: "Docker",
  domains: "域名",
  download: "下載",
  drain: "排空",
  duck: "閃避",
  duration: "時長",
  edit: "編輯",
  effort: "力度",
  enabled: "啓用",
  enforcement: "執行",
  engine: "引擎",
  env: "環境變量",
  environment: "環境",
  ephemeral: "臨時的",
  events: "事件",
  exact: "精確",
  exchanges: "交換",
  existing: "現有的",
  explainer: "解釋器",
  external: "外部",
  extra: "額外",
  extract: "提取",
  fail: "失敗",
  failure: "失敗",
  fallback: "降級",
  fields: "字段",
  file: "文件",
  files: "文件",
  filter: "過濾",
  final: "最終",
  first: "首個",
  for: "用於",
  force: "強制",
  forward: "轉發",
  free: "免費",
  fresh: "新鮮",
  freshness: "新鮮度",
  gain: "增益",
  gateway: "網關",
  gpt55: "GPT5.5",
  guard: "守衛",
  guardrail: "護欄",
  guidance: "引導",
  guild: "服務器",
  hard: "硬",
  hash: "哈希",
  hint: "提示",
  history: "歷史",
  hooks: "鉤子",
  host: "主機",
  hours: "小時",
  hygiene: "衛生",
  id: "ID",
  idempotent: "冪等",
  identifier: "標識符",
  idle: "空閒",
  image: "圖片",
  in: "在",
  inactivity: "不活躍",
  indicator: "指示器",
  inherit: "繼承",
  init: "初始化",
  inline: "內聯",
  input: "輸入",
  install: "安裝",
  installs: "安裝",
  interactive: "交互式",
  interface: "接口",
  interim: "臨時",
  interval: "間隔",
  ipv4: "IPv4",
  iterations: "迭代",
  jobs: "任務",
  json: "JSON",
  keep: "保持",
  key: "密鑰",
  language: "語言",
  last: "最近",
  lazy: "懶加載",
  length: "長度",
  level: "級別",
  limit: "限制",
  line: "行",
  lines: "行",
  local: "本地",
  log: "日誌",
  loopback: "環回",
  managed: "託管",
  markdown: "Markdown",
  max: "最大",
  mb: "MB",
  mcp: "MCP",
  media: "媒體",
  memory: "記憶",
  mention: "@",
  message: "消息,",
  messages: "消息",
  min: "最小",
  modal: "模態框",
  mode: "模式",
  model: "模型",
  mount: "掛載",
  ms: "毫秒",
  mutation: "變更",
  n: "N",
  no: "無",
  non: "非",
  notices: "通知",
  notify: "通知",
  nudge: "輕推",
  on: "開啓",
  only: "僅",
  open: "打開",
  orchestrator: "編排器",
  orphans: "孤兒",
  output: "輸出",
  override: "覆蓋",
  parallel: "並行",
  passthrough: "透傳",
  password: "密碼",
  paste: "粘貼",
  path: "路徑",
  pct: "百分比",
  per: "每次",
  persist: "持久化",
  persistence: "持久化",
  persistent: "持久化的",
  persona: "人設",
  personality: "性格",
  phrases: "短語",
  pii: "PII",
  policy: "策略",
  portal: "門戶",
  pre: "預",
  prefill: "預填充",
  preview: "預覽",
  private: "私有",
  probe: "探針",
  processing: "處理",
  profile: "配置檔",
  progress: "進度",
  project: "項目",
  prompt: "提示詞",
  prompts: "提示詞",
  protect: "保護",
  provider: "提供方",
  providers: "提供商",
  prune: "清理",
  public: "公開",
  rate: "速率",
  ratio: "比例",
  reactions: "回應",
  read: "讀取",
  reasoning: "推理",
  recent: "最近",
  record: "記錄",
  recording: "錄製",
  redact: "脫敏",
  ref: "引用",
  refresh: "刷新",
  region: "區域",
  reload: "重載",
  require: "需要",
  response: "回復",
  restart: "重啓",
  resume: "恢復",
  retention: "保留",
  retries: "重試",
  rewrite: "重寫",
  role: "角色",
  rooms: "房間",
  rotate: "輪換",
  run: "運行",
  s: "秒",
  same: "相同",
  sample: "採樣",
  score: "分數",
  search: "搜索",
  seconds: "秒",
  secret: "機密",
  secrets: "機密",
  server: "服務器",
  service: "服務",
  session: "會話",
  sessions: "會話",
  shared: "共享",
  shell: "Shell",
  shortcut: "快捷鍵",
  show: "顯示",
  silence: "靜音",
  singularity: "奇點",
  size: "大小",
  skin: "皮膚",
  skip: "跳過",
  slash: "斜槓",
  snapshots: "快照",
  source: "來源",
  spawn: "派生",
  speech: "語音",
  stale: "過時",
  status: "狀態",
  stop: "停止",
  strategy: "策略",
  stream: "流式",
  streaming: "流式傳輸",
  strict: "嚴格",
  subagent: "子代理",
  summary: "總結",
  system: "系統",
  tab: "標籤頁",
  tag: "標籤",
  tags: "標籤",
  target: "目標",
  task: "任務",
  template: "模板",
  text: "文本",
  theme: "主題",
  thread: "線程",
  threshold: "閾值",
  tick: "跳動",
  tier: "層級",
  timeout: "超時",
  timestamps: "時間戳",
  timezone: "時區",
  tirith: "Tirith",
  to: "到",
  token: "Token",
  tool: "工具",
  toolsets: "工具集",
  total: "總計",
  trace: "追蹤",
  transport: "傳輸",
  trust: "信任",
  ttl: "TTL",
  tts: "TTS",
  tui: "TUI",
  turn: "輪次",
  turns: "輪次",
  update: "更新",
  url: "URL",
  urls: "URL",
  use: "使用",
  user: "用戶",
  username: "用戶名",
  vacuum: "清理",
  vars: "變量",
  verifier: "驗證器",
  version: "版本",
  voice: "聲音",
  volumes: "卷",
  wait: "等待",
  warning: "警告",
  warnings: "警告",
  worker: "工作者",
  workspace: "工作區",
  wrap: "換行",
  write: "寫入",
};

const ZH_HANT_DESCRIPTIONS: Record<string, string> = {
  model: "默認使用的模型，例如 anthropic/claude-sonnet-4.6。",
  model_context_length: "手動覆蓋上下文窗口；0 表示根據模型元數據自動判斷。",
  "agent.max_turns": "單次任務允許的最大工具調用/模型循環輪次。",
  "agent.gateway_timeout": "網關中代理完全空閒多久後視爲超時，單位秒。",
  "agent.native_image_max_base64_bytes": "原生圖片傳給主模型前的主動壓縮閾值，單位爲 base64 字節；0 表示關閉主動壓縮。",
  "agent.restart_drain_timeout": "網關重啓時等待正在運行任務收尾的最長時間，單位秒。",
  "dashboard.theme": "Web Dashboard 的視覺主題。",
  "dashboard.show_token_analytics": "顯示本地估算的 token/cost 統計；該數值不是賬單口徑。",
  "dingtalk.agent_id": "釘釘企業內部應用 AgentId；當前僅保存並透傳，後續接工作通知等 API 時使用。",
  "dingtalk.allow_all_users": "允許所有釘釘用戶通過網關鑑權；關閉時應配置用戶 allowlist。",
  "dingtalk.allowed_chats": "僅允許這些釘釘羣觸發機器人，多個 ID 用逗號分隔。",
  "dingtalk.allowed_users": "允許的釘釘 staff_id 或 sender_id，多個值用逗號分隔；* 表示任意用戶。",
  "dingtalk.app_code": "釘釘應用 appCode；當前僅保存並透傳，現有 Stream 機器人收發不讀取它。",
  "dingtalk.card_content_key": "釘釘 AI Card 模板中用於承載回復內容的變量名；留空時使用 msgContent。",
  "dingtalk.card_template_id": "釘釘 AI Card 模板 ID；留空時使用釘釘 SDK 默認 Markdown 卡片。",
  "dingtalk.corp_id": "釘釘企業 CorpId；當前僅保存並透傳，後續接企業級開放接口時使用。",
  "dingtalk.free_response_chats": "這些釘釘羣裏無需 @ 機器人也會響應，多個 ID 用逗號分隔。",
  "dingtalk.reply_at_sender": "開啓後，羣聊最終回復會 @ 觸發這輪對話的發送者。",
  "dingtalk.require_mention": "開啓後，釘釘羣聊裏只有 @ 機器人時才響應。",
  "terminal.backend": "工具執行使用的終端後端，例如 local、docker、ssh。",
  "terminal.cwd": "網關和工具執行的默認工作目錄。",
};
function isChinese(locale: Locale): boolean {
  return locale === "zh" || locale === "zh-hant";
}

function getZHData(locale: Locale) {
  if (locale === "zh-hant") {
    return {
      sections: ZH_HANT_SECTION_LABELS,
      fields: ZH_HANT_FIELD_LABELS,
      words: ZH_HANT_FIELD_WORDS,
      descriptions: ZH_HANT_DESCRIPTIONS,
    };
  }
  return {
    sections: ZH_SECTION_LABELS,
    fields: ZH_FIELD_LABELS,
    words: ZH_FIELD_WORDS,
    descriptions: ZH_DESCRIPTIONS,
  };
}


function fallbackSegmentLabel(segment: string): string {
  return segment
    .split("_")
    .filter(Boolean)
    .map((word) => {
      const lower = word.toLowerCase();
      if (ACRONYMS.has(lower)) return lower.toUpperCase();
      return lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join(" ");
}

function fallbackPathLabel(schemaKey: string): string {
  return schemaKey
    .replace(/\./g, " → ")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function translateSegment(segment: string, locale: Locale, kind: "field" | "section"): string {
  if (!isChinese(locale)) return fallbackSegmentLabel(segment);
  const data = getZHData(locale);
  if (kind === "section" && data.sections[segment]) return data.sections[segment];
  if (kind === "field" && data.fields[segment]) return data.fields[segment];

  const words = segment
    .split("_")
    .filter(Boolean)
    .map((word) => data.words[word.toLowerCase()] ?? "");
  if (words.length > 0 && words.every(Boolean)) return words.join("");
  return fallbackSegmentLabel(segment);
}

export function formatConfigCategoryName(
  category: string,
  t: Translations,
  locale: Locale,
): string {
  const knownCategory = (t.config.categories as Record<string, string>)[category];
  const data = getZHData(locale);
  if (isChinese(locale) && data.sections[category]) return data.sections[category];
  if (knownCategory) return knownCategory;
  return translateSegment(category, locale, "section");
}

export function formatConfigSectionName(section: string, locale: Locale): string {
  return translateSegment(section, locale, "section");
}

export function formatConfigFieldLabel(schemaKey: string, locale: Locale): string {
  const data = getZHData(locale);
  if (isChinese(locale) && data.fields[schemaKey]) return data.fields[schemaKey];
  const rawLabel = schemaKey.split(".").pop() ?? schemaKey;
  return translateSegment(rawLabel, locale, "field");
}

export function formatConfigPathLabel(schemaKey: string, locale: Locale): string {
  return schemaKey
    .split(".")
    .map((part, idx, parts) =>
      idx === parts.length - 1
        ? formatConfigFieldLabel(schemaKey, locale)
        : formatConfigSectionName(part, locale),
    )
    .join(" → ");
}

export function formatConfigDescription(
  schemaKey: string,
  schema: Record<string, unknown>,
  locale: Locale,
): string {
  const data = getZHData(locale);
  if (isChinese(locale) && data.descriptions[schemaKey]) return data.descriptions[schemaKey];

  const description = schema.description ? String(schema.description) : "";
  if (!description) return "";
  if (isChinese(locale) && description === fallbackPathLabel(schemaKey)) {
    return formatConfigPathLabel(schemaKey, locale);
  }
  return description;
}
