import { useMemo } from "react";
import { AlertTriangle, ChevronLeft, Search } from "lucide-react";
import { Badge } from "@nous-research/ui/ui/components/badge";
import { Button } from "@nous-research/ui/ui/components/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@nous-research/ui/ui/components/dialog";
import { Input } from "@nous-research/ui/ui/components/input";
import type { ObserverStatus, PeerGrant, PendingAction, PolicyTraceResponse, ReplicationHealthResponse, RoomSummary, RoomTopologyResponse, RoomWorkspaceResponse } from "@/lib/api";
import { filterRoomInbox, taskProgress } from "./workspace-helpers";

export type RoomPreset = "all" | "needs_action" | "failed" | "running" | "idle";
export type RoomWorkspaceTab = "tasks" | "conversation" | "activity";
export type RoomTaskMode = "list" | "graph" | "attempts";
export type RoomInspector = { kind: "room" } | { kind: "task"; taskId: string } | { kind: "attempt"; attemptIndex: number } | { kind: "event"; eventId: string };
export interface RoomsWorkspaceProps { rooms: readonly RoomSummary[]; selectedRoomId: string | null; workspace: RoomWorkspaceResponse | null; topology?: RoomTopologyResponse | null; observer?: ObserverStatus | null; peerGrants?: readonly PeerGrant[] | null; replicationHealth?: ReplicationHealthResponse | null; policyTrace?: PolicyTraceResponse | null; search: string; preset: RoomPreset; tab: RoomWorkspaceTab; taskMode: RoomTaskMode; inspector: RoomInspector; actionCenterAction?: PendingAction | null; onSearchChange(value:string):void; onPresetChange(value:RoomPreset):void; onSelectRoom(id:string):void; onTabChange(value:RoomWorkspaceTab):void; onTaskModeChange(value:RoomTaskMode):void; onInspectorChange(value:RoomInspector):void; onOpenActionCenter(action:PendingAction):void; onCloseActionCenter():void; onApproveAction(action:PendingAction):void; onDenyAction(action:PendingAction):void; actionBusy?: boolean; className?: string; }

const stamp=(v?:number|null)=>v?new Date(v*1000).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"—";
const tone=(v:string)=>/fail|block|denied|cancel/i.test(v)?"destructive" as const:/complete|success|healthy|ready|armed/i.test(v)?"success" as const:/run|progress/i.test(v)?"default" as const:"outline" as const;
function Choices<T extends string>({value,values,onChange,name}:{value:T;values:readonly T[];onChange(v:T):void;name:string}) { return <div role="group" aria-label={name} className="flex min-w-0 flex-wrap gap-1">{values.map(v=><Button key={v} type="button" size="xs" outlined={v!==value} aria-pressed={v===value} onClick={()=>onChange(v)} className="min-w-0 rounded-none px-2 text-[10px] capitalize">{v.replace("_"," ")}</Button>)}</div>; }
function Inbox({p,rooms}:{p:RoomsWorkspaceProps;rooms:RoomSummary[]}) { return <aside aria-label="Room inbox" className={`min-h-0 flex-col border-border bg-background/30 md:flex md:border-r ${p.selectedRoomId?"hidden":"flex"}`}><div className="border-b border-border p-4"><p className="text-xs uppercase text-text-tertiary">Hermes Agent</p><h2 className="text-2xl font-bold">Rooms</h2><label className="relative mt-4 block"><Search className="absolute left-3 top-2.5 h-4 w-4"/><Input aria-label="Search rooms" value={p.search} onChange={e=>p.onSearchChange(e.target.value)} className="pl-9" placeholder="Search rooms"/></label><div className="mt-3"><Choices value={p.preset} values={["all","needs_action","failed","running","idle"]} onChange={p.onPresetChange} name="Room presets"/></div></div><div className="min-h-0 flex-1 overflow-y-auto p-2">{rooms.map(r=><button key={r.room_id} type="button" aria-current={p.selectedRoomId===r.room_id?"true":undefined} onClick={()=>p.onSelectRoom(r.room_id)} className={`mb-2 w-full border p-3 text-left ${p.selectedRoomId===r.room_id?"border-primary bg-primary/10":"border-border"}`}><strong>{r.name}</strong><small className="float-right">{stamp(r.workspace?.last_activity_at)}</small><span className="block truncate text-xs">{r.workspace?.current_task?.subject??"No active work"}</span>{r.workspace?.task_counts.total?<><span className="mt-2 block h-1 bg-border"><span className="block h-full bg-primary" style={{width:`${taskProgress(r)}%`}}/></span><small>{r.workspace.task_counts.completed} / {r.workspace.task_counts.total} tasks</small>{r.workspace.pending_action_count?<Badge tone="warning" className="float-right">{r.workspace.pending_action_count} action</Badge>:null}</>:null}</button>)}{!rooms.length?<p className="p-6 text-center">No rooms match</p>:null}</div></aside>; }
function Header({p,r}:{p:RoomsWorkspaceProps;r:RoomSummary}) { const c=r.workspace?.task_counts;return <header className="border-b border-border px-4 pt-3"><button type="button" onClick={()=>p.onSelectRoom("")} className="mb-2 inline-flex items-center md:hidden"><ChevronLeft className="h-4 w-4"/> Rooms</button><p className="font-mono text-xs text-text-tertiary">ROOMS / {r.room_id}</p><div className="flex items-start justify-between"><div><h1 className="text-2xl font-bold">{r.name}</h1><p className="text-xs uppercase text-text-secondary">{r.workspace?.current_task?.subject??"Room workspace"}</p></div><Badge tone={r.disbanded_at?"outline":"success"}>{r.disbanded_at?"Closed":"Live"}</Badge></div><div className="mt-3 grid grid-cols-4 divide-x divide-border border-y border-border py-2 text-center text-sm"><span><b>{c?`${c.completed} / ${c.total}`:"—"}</b><small className="block">TASKS</small></span><span><b>{r.workspace?.active_member_count??0}</b><small className="block">ACTIVE</small></span><span><b>{c?.failed??c?.blocked??0}</b><small className="block">BLOCKED</small></span><span><b>{r.workspace?.pending_action_count??0}</b><small className="block">ACTION</small></span></div><div role="tablist" aria-label="Room views">{(["tasks","conversation","activity"] as const).map(v=><button key={v} type="button" role="tab" aria-selected={p.tab===v} onClick={()=>p.onTabChange(v)} className={`border-b-2 px-4 py-3 capitalize ${p.tab===v?"border-primary":"border-transparent text-text-secondary"}`}>{v}</button>)}</div></header>; }
function Tasks({p}:{p:RoomsWorkspaceProps}) { const w=p.workspace!; return <><div className="mb-3 flex justify-between gap-2"><span className="text-xs uppercase">Task workspace</span><Choices value={p.taskMode} values={["list","graph","attempts"]} onChange={p.onTaskModeChange} name="Task modes"/></div>{p.taskMode==="list"?w.tasks.map(t=><div key={t.task_id} className="grid grid-cols-[1fr_auto] border-b border-border p-3"><button type="button" className="text-left" onClick={()=>p.onInspectorChange({kind:"task",taskId:t.task_id})}><b>{t.task_id} · {t.subject}</b><small className="block">{t.blockedBy?.length?`Depends on ${t.blockedBy.join(", ")}`:t.blocks?.length?`Blocks ${t.blocks.join(", ")}`:"No dependencies"}</small></button><span><Badge tone={tone(t.status)}>{t.status}</Badge>{t.pending_actions[0]?<Button type="button" size="xs" onClick={()=>p.onOpenActionCenter(t.pending_actions[0])}>Review</Button>:null}</span></div>):p.taskMode==="attempts"?w.attempts.map((a,i)=><button key={a.identity.turn_id} type="button" onClick={()=>p.onInspectorChange({kind:"attempt",attemptIndex:i})} className="flex w-full justify-between border-b p-3"><span>{a.identity.task_id} · Generation {a.execution_generation}</span><Badge tone={tone(a.status)}>{a.status}</Badge></button>):<div className="space-y-3 border p-4">{w.tasks.map(t=><div key={t.task_id} className="grid grid-cols-[1fr_auto_1fr] gap-2"><span className="text-right">{t.blockedBy?.join(", ")||"start"} →</span><button type="button" onClick={()=>p.onInspectorChange({kind:"task",taskId:t.task_id})}>{t.task_id} · {t.subject}</button><span>→ {t.blocks?.join(", ")||"end"}</span></div>)}</div>}</>; }
function Inspector({ p, r }: { p: RoomsWorkspaceProps; r: RoomSummary }) {
  const w = p.workspace!;
  const attempt = p.inspector.kind === "attempt" ? w.attempts[p.inspector.attemptIndex] : undefined;
  const taskId = p.inspector.kind === "task" ? p.inspector.taskId : attempt?.identity.task_id;
  const task = w.tasks.find((item) =>
    item.task_id === taskId || item.latest_attempt?.identity.task_id === taskId
  );
  const eventId = p.inspector.kind === "event" ? p.inspector.eventId : undefined;
  const event = eventId ? w.activity.find((item) => item.event_id === eventId) : undefined;
  return <aside aria-label="Context inspector" className="border-t border-border p-4 xl:border-l xl:border-t-0">
    <p className="text-xs uppercase">{p.inspector.kind} inspector</p><h2 className="text-xl font-bold">{event?.title ?? task?.subject ?? r.name}</h2>
    {event ? <><p>{event.summary}</p>{event.task_id ? <Button onClick={() => p.onInspectorChange({kind:"task",taskId:event.task_id!})}>Open task</Button> : null}</> : null}
    {task ? <><Badge tone={tone(attempt?.status ?? task.status)}>{attempt?.status ?? task.status}</Badge><p>Assignee: @{task.owner ?? "unassigned"}</p>
      {attempt ? <dl className="text-xs"><div>Room: {attempt.identity.room_id}</div><div>Thread: {attempt.identity.thread_id}</div><div>Turn: {attempt.identity.turn_id}</div><div>Execution generation: {attempt.execution_generation}</div><div>Cancel generation: {attempt.cancel_generation}</div><div>Created: {stamp(attempt.created_at)}</div><div>Updated: {stamp(attempt.updated_at)}</div><div>Started: {stamp(attempt.started_at)}</div><div>Terminal: {stamp(attempt.terminal_at)}</div><div>Settlement: {attempt.settlement_status ?? "—"}</div><div className="text-warning">Payload and result are redacted.</div></dl> : null}
      {task.pending_actions[0] ? <Button onClick={() => p.onOpenActionCenter(task.pending_actions[0])}>Review action</Button> : null}</> : null}
    {!event && !task ? <dl><div>Peer routes: {p.replicationHealth?.ready ?? 0} / {p.replicationHealth?.total_peers ?? p.peerGrants?.length ?? 0}</div><div>Observer: {p.observer?.state ?? "Unknown"}</div><div>Policy events: {p.policyTrace?.event_count ?? 0}</div><div>Topology: {p.topology?.members.length ?? r.members.length}</div></dl> : null}
  </aside>;
}
function ActionDialog({p}:{p:RoomsWorkspaceProps}) { const a=p.actionCenterAction;if(!a)return null;const retry=a.kind==="retry";const safe=Object.fromEntries(Object.entries(a.detail).filter(([key,value])=>["tool_name","scope","task_id","status","execution_generation","step_count","reason"].includes(key)&&(typeof value==="string"||typeof value==="number"||typeof value==="boolean")));return <Dialog open onOpenChange={open=>{if(!open)p.onCloseActionCenter()}}><DialogContent><DialogHeader><DialogTitle>Action Center · {retry?"Retry":a.kind.replace("_"," ")}</DialogTitle><DialogDescription>Requested by @{a.from_handle}</DialogDescription></DialogHeader><p>{a.description}</p><dl className="border border-border p-3 text-xs">{Object.entries(safe).map(([key,value])=><div key={key} className="flex justify-between gap-3"><dt>{key.replaceAll("_"," ")}</dt><dd>{String(value)}</dd></div>)}</dl><p className="text-xs text-text-tertiary">Sensitive action detail is redacted.</p><DialogFooter>{!retry?<Button type="button" outlined disabled={p.actionBusy} onClick={()=>p.onDenyAction(a)}>Deny</Button>:null}<Button type="button" disabled={p.actionBusy} onClick={()=>p.onApproveAction(a)}>{retry?"Retry":"Allow once"}</Button></DialogFooter></DialogContent></Dialog>; }
export function RoomsWorkspace(p: RoomsWorkspaceProps) {
  const rooms = useMemo(() => filterRoomInbox(p.rooms, p.search, p.preset), [p.rooms, p.search, p.preset]);
  const room = p.workspace?.room ?? p.rooms.find((item) => item.room_id === p.selectedRoomId);
  if (!room || !p.workspace) return <div className="grid min-h-[36rem] border border-border md:grid-cols-[17rem_1fr]"><Inbox p={p} rooms={rooms}/><main className="hidden place-items-center md:grid">Select a room</main></div>;
  const actions = p.workspace.pending_actions;
  return <div className={`grid min-h-[36rem] overflow-hidden border border-border md:grid-cols-[17rem_1fr] xl:h-[calc(100vh-8rem)] xl:grid-cols-[18rem_minmax(30rem,1fr)_20rem] ${p.className ?? ""}`}>
    <Inbox p={p} rooms={rooms}/>
    <main className="min-h-0 overflow-y-auto"><Header p={p} r={room}/><section role="tabpanel" className="p-4">
      {actions.length ? <div className="mb-4 space-y-2">{actions.map((action) => <div key={action.action_id} className="flex flex-wrap justify-between gap-2 border border-warning/40 bg-warning/10 p-3"><span><AlertTriangle className="mr-2 inline h-4 w-4"/>{action.kind === "retry" ? "Retry required" : "Action required"} · {action.description}</span><Button size="xs" onClick={() => p.onOpenActionCenter(action)}>Review {action.kind}</Button></div>)}</div> : null}
      {p.tab === "tasks" ? <Tasks p={p}/> : p.tab === "conversation" ? <div className="space-y-3">{p.workspace.conversation.map((item) => <article key={item.event_id} className="border border-border p-3"><b>@{item.actor_id}</b><time className="float-right text-xs">{stamp(item.created_at)}</time><p>{item.text}</p>{item.task_id ? <Button size="xs" onClick={() => p.onInspectorChange({kind:"task",taskId:item.task_id!})}>Open task</Button> : null}</article>)}</div> : <div><h3>Activity / Raw events</h3>{p.workspace.activity.map((item) => <button type="button" key={item.event_id} onClick={() => p.onInspectorChange({kind:"event",eventId:item.event_id})} className="block w-full border-b py-3 text-left"><b>{item.title}</b><p>{item.summary}</p></button>)}<details><summary>Raw events (redacted debug view)</summary><pre className="overflow-auto text-xs">{JSON.stringify(p.workspace.log.events, null, 2)}</pre></details></div>}
    </section></main>
    <Inspector p={p} r={room}/><ActionDialog p={p}/>
  </div>;
}
export default RoomsWorkspace;
